AWSTemplateFormatVersion: "2010-09-09"

Transform: AWS::Serverless-2016-10-31

Parameters:
  ResizerBucket:
    Type: String
  MediBucket:
    Type: String

Resources:
  ResizerLambda:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      CodeUri: ../src
      Runtime: nodejs16.x
      FunctionName: !Ref AWS::StackName
      Timeout: 100
      Policies:
        - AmazonS3ReadOnlyAccess
      Environment:
        Variables:
          NODE_OPTIONS: --enable-source-maps
          MEDIA_BUCKET: !Ref MediBucket
          RESIZER_BUCKET: !Ref ResizerBucket