AWSTemplateFormatVersion: "2010-09-09"

Transform: AWS::Serverless-2016-10-31

Parameters:
  ResizerBucket:
    Type: String
  MediBucket:
    Type: String

Resources:
  ResizerLambda:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      CodeUri: ../src
      Runtime: nodejs16.x
      FunctionName: !Ref AWS::StackName
      Timeout: 300
      MemorySize: 1024
      Policies:
        -
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - s3:Get*
                - s3:List*
                - s3-object-lambda:Get*
                - s3-object-lambda:List*
              Resource: arn:aws:s3:::epsilon-development-092347820172-us-east-1-app-media-bucket
        -
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - 's3:*'
              Resource: arn:aws:s3:::epsilon-resizer
      Environment:
        Variables:
          NODE_OPTIONS: --enable-source-maps
          MEDIA_BUCKET: !Ref MediBucket
          RESIZER_BUCKET: !Ref ResizerBucket
